void parse_input(int argc, char** argv, bool loading=false);

void check_parsed();

vector<string> OptionState::startingpatterns = vector<string>();
vector<string> OptionState::targetpatterns = vector<string>();
vector<int> OptionState::xdims = vector<int>();
vector<int> OptionState::ydims = vector<int>();
vector<int> OptionState::gendepths = vector<int>();
vector<string> OptionState::rulespace = vector<string>();
vector<int> OptionState::allow_evolve = vector<int>();
vector<int> OptionState::enforce_move = vector<int>();
int OptionState::minperiod = 0;
string OptionState::filename = string();
int OptionState::reporting_interval = 0;
bool OptionState::sssssmode = false;
vector<NumericalConditions> OptionState::prune = vector<NumericalConditions>();
vector<NumericalConditions> OptionState::filter = vector<NumericalConditions>();
bool OptionState::append = false;
vector<int> OptionState::nosymm = vector<int>();
vector<int> OptionState::noexp = vector<int>();
string OptionState::sssssfolder="";
RulespaceRep OptionState::incomingrulespace;
vector<string> OptionState::slidingmask = vector<string>();
vector<string> OptionState::staticmask = vector<string>();
vector<pair<int,int>> OptionState::staticmaskoff = vector<pair<int,int>>();
vector<string> OptionState::slidingcomp = vector<string>();
vector<string> OptionState::staticcomp = vector<string>();
vector<pair<int,int>> OptionState::staticcompmaskoff = vector<pair<int,int>>();
vector<string> OptionState::help = vector<string>();
vector<int> OptionState::startingbranchoffset = vector<int>();
string OptionState::savefile = string();
string OptionState::loadedargv = string();
long unsigned int OptionState::randseed = LORGE;